Repository honkit/honkit, pull requests merged in 2024-10, with the labels that each got.

#423 chore(test): disable Node 16/18 tests on Windows
  .github/workflows/test.yml
Labels: Type: CI

#435 Fix pnpm link
  CONTRIBUTING.md
Labels: Type: Documentation

#436 Eslint update
  .eslintignore
  .eslintrc
  CONTRIBUTING.md
  eslint.config.mjs
  package.json
  packages/@honkit/markup-it/.eslintrc
  packages/@honkit/markup-it/eslint.config.mjs
  packages/@honkit/markup-it/package.json
  packages/@honkit/theme-default/.eslintrc
  packages/@honkit/theme-default/eslint.config.mjs
  packages/@honkit/theme-default/package.json
  packages/@honkit/theme-default/src/js/core/storage.js
  packages/@honkit/theme-default/src/js/theme/navigation.js
  pnpm-lock.yaml
Labels: Type: Refactoring

#437 CI: Switch to codeql action v2
  .github/workflows/codeql-analysis.yml
Labels: Type: CI

#441 CI(netlify): add NX_SKIP_NX_CACHE=true
  netlify.toml
Labels: Type: CI

#442 Dark search results
  book.js
  packages/@honkit/honkit-plugin-fontsettings/.gitignore
  packages/@honkit/honkit-plugin-fontsettings/.npmignore
  packages/@honkit/honkit-plugin-fontsettings/LICENSE
  packages/@honkit/honkit-plugin-fontsettings/README.md
  packages/@honkit/honkit-plugin-fontsettings/assets/fontsettings.js
  packages/@honkit/honkit-plugin-fontsettings/eslint.config.mjs
  packages/@honkit/honkit-plugin-fontsettings/index.js
  packages/@honkit/honkit-plugin-fontsettings/less/body.less
  packages/@honkit/honkit-plugin-fontsettings/less/dropdowns.less
  packages/@honkit/honkit-plugin-fontsettings/less/header.less
  packages/@honkit/honkit-plugin-fontsettings/less/navigation.less
  packages/@honkit/honkit-plugin-fontsettings/less/settings.less
  packages/@honkit/honkit-plugin-fontsettings/less/summary.less
  packages/@honkit/honkit-plugin-fontsettings/less/variables.less
  packages/@honkit/honkit-plugin-fontsettings/less/website.less
  packages/@honkit/honkit-plugin-fontsettings/package.json
  packages/honkit/package.json
  packages/honkit/src/__tests__/__snapshots__/snapshot-asciidoc.ts.snap
  packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
  packages/honkit/src/plugins/PluginResolver.ts
  pnpm-lock.yaml
Labels: Type: Bug

#444 docs: use legacy theme for testing
  book.js
  packages/@honkit/honkit-plugin-fontsettings/package.json
Labels: Type: Documentation

#446 fix: Dot start Glossary
  packages/@honkit/markdown-legacy/__tests__/fixtures/GLOSSARY.md
  packages/@honkit/markdown-legacy/__tests__/glossary.js
  packages/honkit/src/__tests__/__fixtures__/README.md
  packages/honkit/src/__tests__/__fixtures__/honkit/docs/GLOSSARY.md
  packages/honkit/src/__tests__/__fixtures__/honkit/docs/README.md
  packages/honkit/src/__tests__/__snapshots__/snapshot-honkit.ts.snap
  packages/honkit/src/output/modifiers/__tests__/annotateText.ts
  packages/honkit/src/output/modifiers/annotateText.ts
Labels: Type: Bug

#448 docs(styles): add style config docs
  docs/config.md
  docs/themes/README.md
Labels: Type: Documentation

#450 docs(changelog): point to releases for changelog
  CHANGELOG.md
  docs/SUMMARY.md
Labels: Type: Website
